spring:
  datasource:
    hikari: # Hikari 连接池全局配置
      connection-timeout: 30000     # 等待连接池分配链接的最大时长（毫秒），超过这个时长还没有可用的连接则发生 SQLException，默认：30 秒
      minimum-idle: 1               # 最小空闲连接数
      maximum-pool-size: 10         # 最大连接数
      idle-timeout: 600000          # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
      max-lifetime: 1800000         # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认： 30 分钟
      connection-test-query: SELECT 1


    # Postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_love
    username: postgres
    password: y9C6ZEZWw7
